# -*- coding: utf-8 -*-
"""Persian_Speech_To_Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jksWkyy0IVet0kv1nt6Y0qJSoiUulns
"""

pip install openai-whisper

import whisper

# ۱. انتخاب مدل (مدل small یا medium برای فارسی عالی هستند)
# اگر سرعت برایت مهم است از small و اگر دقت خیلی بالا می‌خواهی از medium استفاده کن
print("در حال بارگذاری هوش مصنوعی... (کمی صبر کنید)")
model = whisper.load_model("small")

# ۲. تبدیل فایل صوتی به متن
print("در حال پردازش فایل صوتی فارسی...")
# نام فایل را اینجا دقیق بنویس
result = model.transcribe("AudioFile.mp4", language="fa")

# ۳. نمایش نتیجه
print("\n--- متن استخراج شده ---\n")
print(result["text"])